name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust Toolchain
        run: |
          rustup update --no-self-update stable
          rustup update --no-self-update nightly
          rustup component add --toolchain nightly clippy rustfmt
          rustup default stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Format Check
        run: cargo +nightly fmt -- --check

      - name: Lint
        run: cargo +nightly clippy --all-targets --all-features -- -D warnings

      - name: Check TODOs
        run: bash .github/workflows/scripts/check_todos.sh

      - name: Build
        run: cargo build --quiet

      - name: Test
        run: cargo test

      - name: Bench
        run: cargo +nightly bench
